# Generated by Django 4.2.9 on 2024-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdetails',
            name='number_of_employee',
            field=models.IntegerField(blank=True, default=0, max_length=12, null=True),
        ),
    ]
