# Generated by Django 4.2.9 on 2024-02-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0002_alter_organizationdetails_number_of_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreation',
            name='company_employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
