# Generated by Django 4.2.9 on 2024-02-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0003_alter_usercreation_company_employee_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
