# Generated by Django 4.2.9 on 2024-02-17 10:30

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0004_delete_taskstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
                ('fixed_state', models.CharField(choices=[('Reopen', 'Reopen'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Client_action_pending', 'Client Action Pending')], default='Reopen', max_length=25)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.organizationdetails')),
                ('user_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
