# Generated by Django 4.2.9 on 2024-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0006_alter_taskstatus_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='fixed_state',
            field=models.CharField(choices=[('Reopen', 'Reopen'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Client Action Pending', 'Client Action Pending')], default='Reopen', max_length=25),
        ),
    ]
