# Generated by Django 4.2.9 on 2024-02-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0009_alter_taskstatus_fixed_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='status',
            new_name='status_name',
        ),
    ]
