# Generated by Django 4.2.9 on 2024-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0011_bgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimage',
            name='image',
            field=models.ImageField(default=None, upload_to='employee/bg_images/'),
        ),
    ]
