# Generated by Django 4.2.9 on 2024-02-21 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0012_alter_bgimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
