# Generated by Django 4.2.9 on 2024-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0013_alter_bgimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='reopen',
            field=models.BooleanField(default=0),
        ),
    ]
