# Generated by Django 4.2.9 on 2024-02-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0014_tasks_reopen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='reopen',
            new_name='reopened_count',
        ),
    ]
