# Generated by Django 4.2.9 on 2024-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0015_rename_reopen_tasks_reopened_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
