# Generated by Django 4.2.9 on 2024-02-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0016_alter_tasks_reopened_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='fixed_state',
            field=models.CharField(choices=[('Reopen', 'Reopen'), ('InProgress', 'InProgress'), ('InReview', 'InReview'), ('OnHold', 'OnHold'), ('Closed', 'Closed'), ('Client Action Pending', 'Client Action Pending')], default='Reopen', max_length=25),
        ),
    ]
