# Generated by Django 4.2.9 on 2024-02-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0018_alter_tasks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskchecklist',
            name='status',
        ),
    ]
