# Generated by Django 4.2.9 on 2024-02-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0019_remove_taskchecklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklist',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digielves_setup.taskstatus'),
        ),
    ]
