# Generated by Django 4.2.9 on 2024-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0022_organizationsubscriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscriptionrequest',
            name='approval_phase',
            field=models.CharField(blank=True, choices=[(2, '2'), (1, '1')], default=1, max_length=10, null=True),
        ),
    ]
