# Generated by Django 4.2.9 on 2024-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0023_organizationsubscriptionrequest_approval_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscriptionrequest',
            name='subscription_want',
            field=models.IntegerField(),
        ),
    ]
