# Generated by Django 4.2.9 on 2024-02-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0024_alter_organizationsubscriptionrequest_subscription_want'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchatting',
            name='message',
            field=models.TextField(),
        ),
    ]
