# Generated by Django 4.2.9 on 2024-02-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0025_alter_taskchatting_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchatting',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
