# Generated by Django 4.2.9 on 2024-03-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0027_alter_taskchatting_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='manager_after_onBoard',
        ),
        migrations.RemoveField(
            model_name='usercreation',
            name='manager_before_onBoard',
        ),
    ]
