# Generated by Django 4.2.9 on 2024-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0028_remove_usercreation_manager_after_onboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='reporting_hierarchy',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
