# Generated by Django 4.2.9 on 2024-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0029_usercreation_reporting_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreation',
            name='reporting_hierarchy',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
