# Generated by Django 4.2.9 on 2024-03-06 12:53

import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0033_remove_usercreation_reporting_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('reporting_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_to_relationships', to='digielves_setup.usercreation')),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_relationships', to='digielves_setup.usercreation')),
            ],
        ),
        migrations.AddField(
            model_name='usercreation',
            name='reporting_to',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='report_to', through='digielves_setup.ReportingRelationship', to='digielves_setup.usercreation'),
        ),
    ]
