# Generated by Django 4.2.9 on 2024-03-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0034_reportingrelationship_usercreation_reporting_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='reporting_hierarchy',
        ),
    ]
