# Generated by Django 4.2.9 on 2024-03-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0035_remove_usercreation_reporting_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdays',
            name='bdCard',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='employee/birthday_cards/'),
        ),
    ]
