# Generated by Django 4.2.9 on 2024-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0036_birthdays_bdcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='fixed_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('InReview', 'InReview'), ('OnHold', 'OnHold'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Client Action Pending', 'Client Action Pending')], default='Pending', max_length=25),
        ),
    ]
