# Generated by Django 4.2.9 on 2024-03-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0037_alter_taskstatus_fixed_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttasks',
            name='inTrash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='inTrash',
            field=models.BooleanField(default=False),
        ),
    ]
