# Generated by Django 4.2.9 on 2024-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0038_checklisttasks_intrash_taskchecklist_intrash'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttasks',
            name='trashed_with',
            field=models.CharField(blank=True, choices=[('Manually', 'Manually'), ('Relatively_task', 'Relatively_task'), ('Relatively_checklist', 'Relatively_checklist')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='trashed_with',
            field=models.CharField(blank=True, choices=[('Manually', 'Manually'), ('Relatively', 'Relatively')], default=None, max_length=20, null=True),
        ),
    ]
