# Generated by Django 4.2.9 on 2024-03-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0039_checklisttasks_trashed_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchecklist',
            name='trashed_with',
            field=models.CharField(blank=True, choices=[('Manually', 'Manually'), ('Relatively_task', 'Relatively_task')], default=None, max_length=20, null=True),
        ),
    ]
