# Generated by Django 4.2.9 on 2024-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0040_alter_taskchecklist_trashed_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttasks',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
