# Generated by Django 4.2.9 on 2024-04-02 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0041_checklisttasks_reopened_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklist',
            name='assign_to',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='assign_to_checklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='due_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
