# Generated by Django 4.2.9 on 2024-04-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0042_taskchecklist_assign_to_taskchecklist_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklist',
            name='urgent_status',
            field=models.BooleanField(default=False),
        ),
    ]
