# Generated by Django 4.2.9 on 2024-04-03 06:57

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0043_taskchecklist_urgent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='status',
            field=models.CharField(blank=True, choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Contacted', 'Contacted'), ('InProgress', 'InProgress'), ('Qualified', 'Qualified'), ('Lost', 'Lost'), ('PendingApproval', 'Pending Approval'), ('Won', 'Won')], default='Unassigned', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SalesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=25)),
                ('fixed_state', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Contacted', 'Contacted'), ('InProgress', 'InProgress'), ('Qualified', 'Qualified'), ('Lost', 'Lost'), ('PendingApproval', 'PendingApproval'), ('Won', 'Won')], default='Unassigned', max_length=25)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.organizationdetails')),
                ('user_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
