# Generated by Django 4.2.9 on 2024-04-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0044_alter_saleslead_status_salesstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleslead',
            name='completed',
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digielves_setup.salesstatus'),
        ),
    ]
