# Generated by Django 4.2.9 on 2024-04-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0046_alter_salesstatus_fixed_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesstatus',
            name='fixed_state',
        ),
    ]
