# Generated by Django 4.2.9 on 2024-04-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0047_remove_salesstatus_fixed_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesstatus',
            name='fixed_state',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('Contacted', 'Contacted'), ('InProgress', 'InProgress'), ('Qualified', 'Qualified'), ('Lost', 'Lost'), ('PendingApproval', 'PendingApproval'), ('Won', 'Won')], default=None, max_length=25),
        ),
    ]
