# Generated by Django 4.2.9 on 2024-04-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0048_salesstatus_fixed_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='due_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
