# Generated by Django 4.2.9 on 2024-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0050_alter_salesstatus_fixed_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='inTrash',
            field=models.BooleanField(default=False),
        ),
    ]
