# Generated by Django 4.2.9 on 2024-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0051_saleslead_intrash'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='urgent_status',
            field=models.BooleanField(default=False),
        ),
    ]
