# Generated by Django 4.2.9 on 2024-04-04 09:58

import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0052_saleslead_urgent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='employee/sales_attachments/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.saleslead')),
            ],
        ),
    ]
