# Generated by Django 4.2.9 on 2024-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0054_alter_tasks_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
