# Generated by Django 4.2.9 on 2024-04-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0055_alter_tasks_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
