# Generated by Django 4.2.9 on 2024-04-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0057_businesscard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscard',
            old_name='user_id',
            new_name='user',
        ),
    ]
