# Generated by Django 4.2.9 on 2024-04-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0060_alter_userfilters_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfilters',
            old_name='board_view',
            new_name='myboard_view',
        ),
    ]
