# Generated by Django 4.2.9 on 2024-04-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0061_rename_board_view_userfilters_myboard_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilters',
            name='custom_board_view',
            field=models.CharField(choices=[('Kanban', 'Kanban'), ('List', 'List')], default='Kanban', max_length=25),
        ),
        migrations.AddField(
            model_name='userfilters',
            name='personal_board_view',
            field=models.CharField(choices=[('Kanban', 'Kanban'), ('List', 'List')], default='Kanban', max_length=25),
        ),
        migrations.AddField(
            model_name='userfilters',
            name='sales_board_view',
            field=models.CharField(choices=[('Kanban', 'Kanban'), ('List', 'List')], default='Kanban', max_length=25),
        ),
    ]
