# Generated by Django 4.2.9 on 2024-04-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0062_userfilters_custom_board_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchecklist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
