# Generated by Django 4.2.9 on 2024-04-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0063_taskchecklist_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttasks',
            name='Task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.tasks'),
        ),
    ]
