# Generated by Django 4.2.9 on 2024-04-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0065_alter_checklisttasks_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttasks',
            name='Task',
        ),
    ]
