# Generated by Django 4.2.9 on 2024-04-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0066_remove_checklisttasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttasks',
            name='Task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.tasks'),
        ),
    ]
