# Generated by Django 4.2.9 on 2024-04-19 09:58

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0067_checklisttasks_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=25)),
                ('fixed_state', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('InReview', 'InReview'), ('OnHold', 'OnHold'), ('Completed', 'Completed')], default='Pending', max_length=25)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_topic', models.CharField(max_length=300)),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('task_description', models.CharField(blank=True, max_length=500, null=True)),
                ('urgent_status', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('sequence', models.CharField(blank=True, max_length=100, null=True)),
                ('is_personal', models.BooleanField(default=True)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('inTrash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digielves_setup.personalstatus')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTaskAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='employee/personal_attachments/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('personaltask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.personaltask')),
            ],
        ),
    ]
