# Generated by Django 4.2.9 on 2024-04-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0068_personalstatus_personaltask_personaltaskattachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltask',
            old_name='user_id',
            new_name='user',
        ),
    ]
