# Generated by Django 4.2.9 on 2024-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0070_rename_user_personaltask_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalstatus',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='personaltask',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='personalstatus',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
