# Generated by Django 4.2.9 on 2024-04-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0071_rename_user_id_personalstatus_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltask',
            old_name='user',
            new_name='user_id',
        ),
    ]
