# Generated by Django 4.2.9 on 2024-04-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0072_rename_user_personaltask_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalstatus',
            old_name='user',
            new_name='user_id',
        ),
    ]
