# Generated by Django 4.2.9 on 2024-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0073_rename_user_personalstatus_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltask',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
