# Generated by Django 4.2.9 on 2024-04-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0075_alter_personaltask_is_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttasks',
            name='task_checklist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.taskchecklist'),
        ),
    ]
