# Generated by Django 4.2.9 on 2024-04-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0076_alter_checklisttasks_task_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorconsultation',
            name='prescription_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
