# Generated by Django 4.2.9 on 2024-04-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0077_alter_doctorconsultation_prescription_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorconsultation',
            name='advice',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctorconsultation',
            name='dignosis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
