# Generated by Django 4.2.9 on 2024-04-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0079_extavailableslots_extavailableslotstime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extavailableslots',
            name='date',
            field=models.DateField(),
        ),
    ]
