# Generated by Django 4.2.9 on 2024-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0080_alter_extavailableslots_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extavailableslots',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
