# Generated by Django 4.2.9 on 2024-04-29 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0081_alter_extavailableslots_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttasks',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='project_file_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='project_file_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
