# Generated by Django 4.2.9 on 2024-04-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0084_tasks_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttasks',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
