# Generated by Django 4.2.9 on 2024-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0085_checklisttasks_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='due_datee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
