# Generated by Django 4.2.9 on 2024-04-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0088_alter_tasks_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdays',
            name='bd_wish',
            field=models.TextField(blank=True, null=True),
        ),
    ]
