# Generated by Django 4.2.9 on 2024-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0089_birthdays_bd_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdays',
            name='card_added',
            field=models.BooleanField(default=False),
        ),
    ]
