# Generated by Django 4.2.9 on 2024-05-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0090_birthdays_card_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdays',
            name='card_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
