# Generated by Django 4.2.9 on 2024-05-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0091_birthdays_card_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdays',
            name='profile_picture',
        ),
    ]
