# Generated by Django 4.2.9 on 2024-05-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0092_remove_birthdays_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdays',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='employee/profile/user_rel_birthday_profile/'),
        ),
    ]
