# Generated by Django 4.2.9 on 2024-05-03 06:19

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0093_birthdays_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdCard', models.ImageField(blank=True, default=None, null=True, upload_to='employee/birthday_cards/')),
                ('bd_wish', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('birthday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.birthdays')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
