# Generated by Django 4.2.9 on 2024-05-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0094_birthdaytemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaytemplates',
            name='card_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
