# Generated by Django 4.2.9 on 2024-05-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0095_birthdaytemplates_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaytemplates',
            name='card_profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='employee/profile/card_profile/'),
        ),
    ]
