# Generated by Django 4.2.9 on 2024-05-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0096_birthdaytemplates_card_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdays',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='employee/birthday_cards/profile/'),
        ),
        migrations.AlterField(
            model_name='birthdaytemplates',
            name='bdCard',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='employee/birthday_cards/card/'),
        ),
        migrations.AlterField(
            model_name='birthdaytemplates',
            name='card_profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='employee/birthday_cards/profile/custom_profile/'),
        ),
    ]
