# Generated by Django 4.2.9 on 2024-05-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0097_alter_birthdays_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdays',
            name='bdCard',
        ),
        migrations.RemoveField(
            model_name='birthdays',
            name='bd_wish',
        ),
        migrations.RemoveField(
            model_name='birthdays',
            name='card_name',
        ),
    ]
