# Generated by Django 4.2.9 on 2024-05-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0098_remove_birthdays_bdcard_remove_birthdays_bd_wish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttasks',
            name='due_datee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
