# Generated by Django 4.2.9 on 2024-05-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0101_checklisttasks_due_datee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttasks',
            name='due_datee',
        ),
    ]
