# Generated by Django 4.2.9 on 2024-05-03 12:57

import digielves_setup.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0102_remove_checklisttasks_due_datee'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttasks',
            name='due_datee',
            field=digielves_setup.models.UTCDateTimeField(blank=True, null=True),
        ),
    ]
