# Generated by Django 4.2.9 on 2024-05-04 08:11

import digielves_setup.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0103_checklisttasks_due_datee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_datee',
            field=digielves_setup.models.UTCDateTimeField(blank=True, null=True),
        ),
    ]
