# Generated by Django 4.2.9 on 2024-05-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0104_alter_tasks_due_datee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='due_date',
            new_name='due_date_exiting',
        ),
    ]
