# Generated by Django 4.2.9 on 2024-05-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0105_rename_due_date_tasks_due_date_exiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='due_datee',
            new_name='due_date',
        ),
    ]
