# Generated by Django 4.2.9 on 2024-05-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0106_rename_due_datee_tasks_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklisttasks',
            old_name='due_date',
            new_name='due_date_existing',
        ),
    ]
