# Generated by Django 4.2.9 on 2024-05-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0107_rename_due_date_checklisttasks_due_date_existing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklisttasks',
            old_name='due_datee',
            new_name='due_date',
        ),
    ]
