# Generated by Django 4.2.9 on 2024-05-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0108_rename_due_datee_checklisttasks_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='summeryndtask',
            name='summery_generated',
            field=models.BooleanField(default=False),
        ),
    ]
