# Generated by Django 4.2.9 on 2024-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0110_checklisttasks_due_date_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='due_date_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
