# Generated by Django 4.2.9 on 2024-05-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0111_tasks_due_date_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklisttasks',
            old_name='due_date',
            new_name='due_date_latest_existing',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='due_date',
            new_name='due_date_latest_existing',
        ),
    ]
