# Generated by Django 4.2.9 on 2024-05-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0112_rename_due_date_checklisttasks_due_date_latest_existing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklisttasks',
            old_name='due_date_new',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='due_date_new',
            new_name='due_date',
        ),
    ]
