# Generated by Django 4.2.9 on 2024-05-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0113_rename_due_date_new_checklisttasks_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesstatus',
            name='fixed_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Contacted', 'Contacted'), ('InProgress', 'InProgress'), ('Qualified', 'Qualified'), ('Lost', 'Lost'), ('PendingApproval', 'PendingApproval'), ('Won', 'Won')], default=None, max_length=25),
        ),
    ]
