# Generated by Django 4.2.9 on 2024-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0114_alter_salesstatus_fixed_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
