# Generated by Django 4.2.9 on 2024-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0115_board_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='due_date_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
