# Generated by Django 4.2.9 on 2024-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0116_saleslead_due_date_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='due_date_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
