# Generated by Django 4.2.9 on 2024-05-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0117_personaltask_due_date_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltask',
            name='due_date',
        ),
    ]
