# Generated by Django 4.2.9 on 2024-05-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0118_remove_personaltask_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltask',
            old_name='due_date_new',
            new_name='due_date',
        ),
    ]
