# Generated by Django 4.2.9 on 2024-05-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0119_rename_due_date_new_personaltask_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecklistTasks',
            new_name='SubTasks',
        ),
    ]
