# Generated by Django 4.2.9 on 2024-05-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0120_rename_checklisttasks_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtasks',
            name='task_checklist',
        ),
    ]
