# Generated by Django 4.2.9 on 2024-05-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0121_remove_subtasks_task_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskchecklist',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='taskchecklist',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='taskchecklist',
            name='project_file_name',
        ),
        migrations.RemoveField(
            model_name='taskchecklist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskchecklist',
            name='urgent_status',
        ),
    ]
