# Generated by Django 4.2.9 on 2024-05-23 07:29

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0122_remove_taskchecklist_assign_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTaskChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_topic', models.CharField(blank=True, max_length=300, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('task_description', models.CharField(blank=True, max_length=200, null=True)),
                ('urgent_status', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('inTrash', models.BooleanField(default=False)),
                ('trashed_with', models.CharField(blank=True, choices=[('Manually', 'Manually'), ('Relatively_task', 'Relatively_task'), ('Relatively_checklist', 'Relatively_checklist')], default=None, max_length=20, null=True)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('assign_to', models.ManyToManyField(blank=True, default=None, null=True, related_name='assign_to_subtask_child', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_child_created_by', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digielves_setup.taskstatus')),
                ('subtasks', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.subtasks')),
            ],
        ),
    ]
