# Generated by Django 4.2.9 on 2024-05-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('digielves_setup', '0125_userposition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='DueRequest',
        ),
    ]
