# Generated by Django 4.2.9 on 2024-05-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0126_rename_request_duerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duerequest',
            name='receivers',
        ),
    ]
