# Generated by Django 4.2.9 on 2024-05-24 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0127_remove_duerequest_receivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='duerequest',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
