# Generated by Django 4.2.9 on 2024-05-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0128_duerequest_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duerequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='duerequest',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='duerequest',
            name='object_id',
        ),
    ]
