# Generated by Django 4.2.9 on 2024-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0129_remove_duerequest_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duerequest',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='duerequest',
            name='proposed_value',
        ),
        migrations.AddField(
            model_name='duerequest',
            name='current_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duerequest',
            name='proposed_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
