# Generated by Django 4.2.9 on 2024-05-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0130_remove_duerequest_current_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duerequest',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.tasks'),
        ),
    ]
