# Generated by Django 4.2.9 on 2024-05-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0131_duerequest_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='duerequest',
            name='inTrash',
            field=models.BooleanField(default=False),
        ),
    ]
