# Generated by Django 4.2.9 on 2024-05-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0133_gmailemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='duerequest',
            name='subtaskchild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.subtaskchild'),
        ),
        migrations.AddField(
            model_name='duerequest',
            name='subtasks',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.subtasks'),
        ),
        migrations.AlterField(
            model_name='duerequest',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.tasks'),
        ),
    ]
