# Generated by Django 4.2.9 on 2024-05-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0134_duerequest_subtaskchild_duerequest_subtasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='system_assigned',
            field=models.BooleanField(default=True),
        ),
    ]
