# Generated by Django 4.2.9 on 2024-05-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0135_subtasks_system_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks',
            name='system_assigned',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
