# Generated by Django 4.2.9 on 2024-05-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0136_alter_subtasks_system_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtasks',
            name='system_assigned',
        ),
    ]
