# Generated by Django 4.2.9 on 2024-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0139_alter_subtasks_system_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskchild',
            name='system_assigned',
            field=models.BooleanField(default=True),
        ),
    ]
