# Generated by Django 4.2.9 on 2024-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0141_organizationworkschedule_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationworkschedule',
            name='working_hours',
            field=models.IntegerField(default=0),
        ),
    ]
