# Generated by Django 4.2.9 on 2024-06-05 05:43

import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0142_organizationworkschedule_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleslead',
            old_name='due_date',
            new_name='due_date_existing',
        ),
        migrations.CreateModel(
            name='SalesFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.saleslead')),
            ],
        ),
    ]
