# Generated by Django 4.2.9 on 2024-06-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0143_rename_due_date_saleslead_due_date_existing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleslead',
            old_name='due_date_new',
            new_name='due_date',
        ),
    ]
