# Generated by Django 4.2.9 on 2024-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0144_rename_due_date_new_saleslead_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='lead_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='reference_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
