# Generated by Django 4.2.9 on 2024-06-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0145_saleslead_company_name_saleslead_lead_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleslead',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='saleslead',
            name='due_date_existing',
        ),
    ]
