# Generated by Django 4.2.9 on 2024-06-05 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0146_remove_saleslead_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='lead_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
