# Generated by Django 4.2.9 on 2024-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0147_saleslead_lead_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
