# Generated by Django 4.2.9 on 2024-06-05 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0149_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
