# Generated by Django 4.2.9 on 2024-06-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0150_alter_policies_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies',
            name='disease',
        ),
    ]
