# Generated by Django 4.2.9 on 2024-06-05 12:17

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0151_remove_policies_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLeadSpecialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'view'), ('edit', 'edit')], default='view', max_length=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('access_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_to_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SalesFollowUp',
        ),
    ]
