# Generated by Django 4.2.9 on 2024-06-05 12:18

import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0152_salesleadspecialaccess_delete_salesfollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.saleslead')),
            ],
        ),
    ]
