# Generated by Django 4.2.9 on 2024-06-06 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0153_salesfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfollowup',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
