# Generated by Django 4.2.9 on 2024-06-06 08:55

import datetime
import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('digielves_setup', '0155_userworkschedule_userweekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10)),
                ('freeze', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='userworkschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='userworkschedule',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='userworkschedule',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='userworkschedule',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.DeleteModel(
            name='UserWeekday',
        ),
        migrations.AddField(
            model_name='userworkslot',
            name='userworkschedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.userworkschedule'),
        ),
    ]
