# Generated by Django 4.2.9 on 2024-06-06 10:04

import datetime
import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0156_userworkslot_remove_userworkschedule_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=15, null=True)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
