# Generated by Django 4.2.9 on 2024-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0157_usercalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercalender',
            name='unique_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
