# Generated by Django 4.2.9 on 2024-06-06 10:36

import datetime
import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('digielves_setup', '0158_usercalender_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalenderReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=15, null=True)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('unique_id', models.PositiveIntegerField(default=None)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCalender',
        ),
    ]
