# Generated by Django 4.2.9 on 2024-06-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('digielves_setup', '0159_usercalenderreminder_delete_usercalender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCalenderReminder',
            new_name='CalenderReminder',
        ),
    ]
