# Generated by Django 4.2.9 on 2024-06-06 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0160_rename_usercalenderreminder_calenderreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='calenderreminder',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='shared_with_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
