# Generated by Django 4.2.9 on 2024-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0161_calenderreminder_shared_with_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calenderreminder',
            old_name='unique_id',
            new_name='platform_id',
        ),
        migrations.AlterField(
            model_name='calenderreminder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
