# Generated by Django 4.2.9 on 2024-06-06 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0162_rename_unique_id_calenderreminder_platform_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calenderreminder',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='calenderreminder',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='calenderreminder',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='calenderreminder',
            name='to_time',
        ),
        migrations.AddField(
            model_name='calenderreminder',
            name='from_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calenderreminder',
            name='to_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
