# Generated by Django 4.2.9 on 2024-06-06 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0163_remove_calenderreminder_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderreminder',
            name='from_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='calenderreminder',
            name='platform_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
