# Generated by Django 4.2.9 on 2024-06-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0164_alter_calenderreminder_from_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calenderreminder',
            name='shared_with_users',
        ),
    ]
