# Generated by Django 4.2.9 on 2024-06-06 12:05

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('digielves_setup', '0166_calenderreminder_shared_with_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderReminderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=15, null=True)),
                ('from_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('to_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('shared_with_users', models.ManyToManyField(blank=True, default=None, null=True, related_name='shared_with_users_test', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
