# Generated by Django 4.2.9 on 2024-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0167_calenderremindertest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderremindertest',
            name='platform_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
