# Generated by Django 4.2.9 on 2024-06-07 05:46

import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0168_alter_calenderremindertest_platform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calenderreminder',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NextReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_schedule', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('calenderreminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.calenderreminder')),
            ],
        ),
    ]
