# Generated by Django 4.2.9 on 2024-06-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0169_calenderreminder_completed_nextreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NextReminder',
        ),
    ]
