# Generated by Django 4.2.9 on 2024-06-07 05:53

import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0170_delete_nextreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('calendar_reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='digielves_setup.calenderreminder')),
            ],
        ),
    ]
