# Generated by Django 4.2.9 on 2024-06-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0171_reminderschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calenderreminder',
            old_name='Completed',
            new_name='completed',
        ),
    ]
