# Generated by Django 4.2.9 on 2024-06-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0172_rename_completed_calenderreminder_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userworkslot',
            old_name='userworkschedule',
            new_name='user_work_schedule',
        ),
    ]
