# Generated by Django 4.2.9 on 2024-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0173_rename_userworkschedule_userworkslot_user_work_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkslot',
            name='slot',
            field=models.CharField(max_length=15),
        ),
    ]
