# Generated by Django 4.2.9 on 2024-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0175_alter_userworkslot_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkslot',
            name='reschedule',
            field=models.BooleanField(default=False),
        ),
    ]
