# Generated by Django 4.2.9 on 2024-06-08 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0177_extensionmeetingdateoptions_extensiondateslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionmeetingdateoptions',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
