# Generated by Django 4.2.9 on 2024-06-10 06:53

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0178_extensionmeetingdateoptions_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsiderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100)),
                ('processed', models.CharField(blank=True, choices=[(2, '2'), (1, '1'), (0, '0')], default=0, max_length=20, null=True)),
                ('verified', models.CharField(blank=True, choices=[(2, '2'), (1, '1'), (0, '0')], default=0, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(db_column='added_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='added_by_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
