# Generated by Django 4.2.9 on 2024-06-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0179_outsideruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutsiderUser',
        ),
    ]
