# Generated by Django 4.2.9 on 2024-06-10 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0181_outsideruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideruser',
            name='related_id',
            field=models.ForeignKey(blank=True, db_column='related_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
