# Generated by Django 4.2.9 on 2024-06-10 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0182_outsideruser_related_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideruser',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
