# Generated by Django 4.2.9 on 2024-06-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0183_alter_outsideruser_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideruser',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_id', to='digielves_setup.organizationdetails'),
        ),
    ]
