# Generated by Django 4.2.9 on 2024-06-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0184_outsideruser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideruser',
            name='approval_user_role',
            field=models.CharField(blank=True, default='Employee', max_length=20, null=True),
        ),
    ]
