# Generated by Django 4.2.9 on 2024-06-10 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0185_outsideruser_approval_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='next_followup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
