# Generated by Django 4.2.9 on 2024-06-10 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0186_saleslead_next_followup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='next_followup_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
