# Generated by Django 4.2.9 on 2024-06-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0187_alter_saleslead_next_followup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideruser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsideruser',
            name='employee_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsideruser',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
