# Generated by Django 4.2.9 on 2024-06-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0188_outsideruser_dob_outsideruser_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideruser',
            name='processed',
            field=models.CharField(blank=True, choices=[(3, '3'), (2, '2'), (1, '1'), (0, '0')], default=0, max_length=20, null=True),
        ),
    ]
