# Generated by Django 4.2.9 on 2024-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0189_alter_outsideruser_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideruser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee/outsider/profile/'),
        ),
    ]
