# Generated by Django 4.2.9 on 2024-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0190_outsideruser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideruser',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='outsideruser',
            name='designation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
