# Generated by Django 4.2.9 on 2024-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0191_outsideruser_department_outsideruser_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionmeetingdateoptions',
            name='platform',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
