# Generated by Django 4.2.9 on 2024-06-11 09:49

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0192_extensionmeetingdateoptions_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_category', models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], max_length=10)),
                ('policy_number', models.CharField(max_length=20, unique=True)),
                ('policy_name', models.CharField(max_length=100)),
                ('insurance_provider_name', models.CharField(max_length=100)),
                ('policy_type', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('group', 'Group')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('policy_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], max_length=20)),
                ('policyholder_name', models.CharField(max_length=100)),
                ('policyholder_dob', models.DateField()),
                ('policyholder_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('policyholder_address', models.TextField()),
                ('policyholder_contact_number', models.CharField(max_length=15)),
                ('policyholder_email_address', models.EmailField(max_length=254)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('next_payment_due_date', models.DateField()),
                ('beneficiary_names', models.TextField()),
                ('beneficiary_relationships', models.TextField()),
                ('beneficiary_contact_info', models.TextField()),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='employee/policy_documents/')),
                ('other_documents', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.organizationdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='employee/policy_documents/other_documents/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='digielves_setup.policy')),
            ],
        ),
        migrations.CreateModel(
            name='InsuredMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('relationship_to_policyholder', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_members', to='digielves_setup.policy')),
            ],
        ),
    ]
