# Generated by Django 4.2.9 on 2024-06-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0193_policy_policydocument_insuredmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='other_documents',
        ),
        migrations.AlterField(
            model_name='policy',
            name='beneficiary_contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='beneficiary_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='beneficiary_relationships',
            field=models.TextField(blank=True, null=True),
        ),
    ]
