# Generated by Django 4.2.9 on 2024-06-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0194_remove_policy_other_documents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policies',
        ),
    ]
