# Generated by Django 4.2.9 on 2024-06-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0195_delete_policies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Policy',
            new_name='Policies',
        ),
    ]
