# Generated by Django 4.2.9 on 2024-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0196_rename_policy_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='beneficiary_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policies',
            name='beneficiary_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='policies',
            name='identification_proof',
            field=models.FileField(blank=True, null=True, upload_to='employee/policy_documents/id_proof/'),
        ),
        migrations.AddField(
            model_name='policies',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='employee/policy_documents/medical_report/'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='policy_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], max_length=20, null=True),
        ),
    ]
