# Generated by Django 4.2.9 on 2024-06-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0197_policies_beneficiary_dob_policies_beneficiary_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='next_payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
