# Generated by Django 4.2.9 on 2024-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0198_alter_policies_coverage_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='policy_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
