# Generated by Django 4.2.9 on 2024-06-11 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0199_alter_policies_policy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideruser',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsideruser',
            name='invited_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
