# Generated by Django 4.2.9 on 2024-06-11 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0200_outsideruser_approved_date_outsideruser_invited_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsideruser',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outsideruser',
            name='invited_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
