# Generated by Django 4.2.9 on 2024-06-12 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0202_taskspecialaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='assign_to_outsider',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='assign_to_outsider', to=settings.AUTH_USER_MODEL),
        ),
    ]
