# Generated by Django 4.2.9 on 2024-06-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0203_tasks_assign_to_outsider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assign_to_outsider',
        ),
    ]
