# Generated by Django 4.2.9 on 2024-06-12 14:09

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0204_remove_tasks_assign_to_outsider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_board', models.BooleanField(default=True)),
                ('can_view_checklists', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('access_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions_to', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.board')),
                ('checklist_permissions', models.ManyToManyField(blank=True, related_name='checklist_permissions', to='digielves_setup.checklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
