# Generated by Django 4.2.9 on 2024-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0205_boardpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='insurance_provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='policy_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('family', 'Family'), ('group', 'Group')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
