# Generated by Django 4.2.9 on 2024-06-12 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0206_alter_policies_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpermission',
            name='access_to',
        ),
        migrations.AddField(
            model_name='boardpermission',
            name='access_to',
            field=models.ManyToManyField(related_name='access_permissions_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
