# Generated by Django 4.2.9 on 2024-06-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0207_remove_boardpermission_access_to_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardPermission',
        ),
    ]
