# Generated by Django 4.2.9 on 2024-06-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0209_boardpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='next_followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
