# Generated by Django 4.2.9 on 2024-06-14 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0210_alter_saleslead_next_followup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_topic', models.CharField(blank=True, max_length=300, null=True)),
                ('task_description', models.CharField(blank=True, max_length=500, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('urgent_status', models.BooleanField(default=False)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('in_trash', models.BooleanField(default=False)),
                ('trashed_with', models.CharField(blank=True, choices=[('Manually', 'Manually'), ('Relatively_task', 'Relatively_task'), ('Relatively_checklist', 'Relatively_checklist')], default=None, max_length=20, null=True)),
                ('system_assigned', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('project_file_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ManyToManyField(blank=True, null=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.checklist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_level_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='digielves_setup.tasklevel')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digielves_setup.taskstatus')),
            ],
        ),
    ]
