# Generated by Django 4.2.9 on 2024-06-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0211_tasklevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskattachments',
            name='attachment',
            field=models.FileField(upload_to='employee/task/'),
        ),
        migrations.AlterField(
            model_name='taskattachments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.tasklevel'),
        ),
    ]
