# Generated by Django 4.2.9 on 2024-06-14 13:36

import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0212_alter_checklist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachments',
            name='attachment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='taskattachments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.tasks'),
        ),
        migrations.CreateModel(
            name='TaskLevelAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='employee/task/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.tasklevel')),
            ],
        ),
    ]
