# Generated by Django 4.2.9 on 2024-06-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0213_alter_taskattachments_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklevelattachments',
            old_name='task',
            new_name='task_level',
        ),
    ]
