# Generated by Django 4.2.9 on 2024-06-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0214_rename_task_tasklevelattachments_task_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskLevelAttachments',
        ),
    ]
