# Generated by Django 4.2.9 on 2024-06-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0215_delete_tasklevelattachments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskLevel',
        ),
    ]
