# Generated by Django 4.2.9 on 2024-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0218_alter_tasklevel_id_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
