# Generated by Django 4.2.9 on 2024-06-14 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0219_alter_tasklevel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklevel',
            name='id',
        ),
        migrations.AddField(
            model_name='tasklevel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
