# Generated by Django 4.2.9 on 2024-06-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0220_remove_tasklevel_id_tasklevel_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklevelattachments',
            name='task_level',
        ),
        migrations.DeleteModel(
            name='Sections',
        ),
        migrations.DeleteModel(
            name='TaskLevelAttachments',
        ),
    ]
