# Generated by Django 4.2.9 on 2024-06-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0221_remove_tasklevelattachments_task_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskLevel',
        ),
    ]
