# Generated by Django 4.2.9 on 2024-06-17 08:15

import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0222_delete_tasklevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStatusTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_status', to='digielves_setup.salesstatus')),
                ('sales_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.saleslead')),
                ('to_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_status', to='digielves_setup.salesstatus')),
            ],
        ),
    ]
