# Generated by Django 4.2.9 on 2024-06-17 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0223_salestatustrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestatustrack',
            name='changed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
