# Generated by Django 4.2.9 on 2024-06-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0224_salestatustrack_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestatustrack',
            name='from_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
