# Generated by Django 4.2.9 on 2024-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0225_salestatustrack_from_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkschedule',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationworkschedule',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
