# Generated by Django 4.2.9 on 2024-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0226_userworkschedule_working_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
