# Generated by Django 4.2.9 on 2024-06-18 07:12

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0227_alter_policies_premium_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInBoardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('access_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_access_permissions_to', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
