# Generated by Django 4.2.9 on 2024-06-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0230_multileveltask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReminderSchedule',
        ),
    ]
