# Generated by Django 4.2.9 on 2024-06-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0231_delete_reminderschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='other_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
