# Generated by Django 4.2.9 on 2024-06-24 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0232_notification_other_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideruser',
            name='secondary_adders',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='secondary_adders', to=settings.AUTH_USER_MODEL),
        ),
    ]
