# Generated by Django 4.2.9 on 2024-06-24 12:46

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0233_outsideruser_secondary_adders'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_topic', models.CharField(max_length=300)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('task_description', models.CharField(blank=True, max_length=500, null=True)),
                ('urgent_status', models.BooleanField(default=False)),
                ('sequence', models.CharField(blank=True, max_length=100, null=True)),
                ('task_level', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('is_personal', models.BooleanField(default=False)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('inTrash', models.BooleanField(default=False)),
                ('project_file_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('assign_to', models.ManyToManyField(blank=True, default=None, null=True, related_name='task_hierarchy_assign_to', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.checklist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_hierarchy_created_by', to=settings.AUTH_USER_MODEL)),
                ('depend_on', models.ManyToManyField(blank=True, null=True, related_name='dependent_children', to='digielves_setup.taskhierarchy')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='digielves_setup.taskhierarchy')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digielves_setup.taskstatus')),
            ],
        ),
    ]
