# Generated by Django 4.2.9 on 2024-06-24 12:50

import digielves_setup.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0234_taskhierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHierarchyAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_attachment', models.FileField(upload_to='employee/task/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.taskhierarchy')),
            ],
        ),
    ]
