# Generated by Django 4.2.9 on 2024-06-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0235_taskhierarchyattachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhierarchy',
            name='task_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
