# Generated by Django 4.2.9 on 2024-06-25 12:04

import digielves_setup.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0237_alter_taskhierarchyattachments_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHierarchyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inTrash', models.BooleanField(default=False)),
                ('trashed_with', models.CharField(blank=True, choices=[('Manually', 'Manually'), ('Relatively_task', 'Relatively_task')], default=None, max_length=20, null=True)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', digielves_setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('Task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_hierarchy_checklist', to='digielves_setup.taskhierarchy')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_hierarchy_checklist_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
