# Generated by Django 4.2.9 on 2024-06-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0238_taskhierarchychecklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskHierarchyTaskComments',
            new_name='TaskHierarchyComments',
        ),
    ]
