# Generated by Django 4.2.9 on 2024-06-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0239_rename_taskhierarchytaskcomments_taskhierarchycomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskHierarchyTaskChatting',
            new_name='TaskHierarchyChatting',
        ),
    ]
