# Generated by Django 4.2.9 on 2024-06-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0240_rename_taskhierarchytaskchatting_taskhierarchychatting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskHierarchyTaskAction',
            new_name='TaskHierarchyAction',
        ),
    ]
