# Generated by Django 4.2.9 on 2024-06-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0241_rename_taskhierarchytaskaction_taskhierarchyaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhierarchy',
            name='depend_on',
        ),
    ]
