# Generated by Django 4.2.9 on 2024-06-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0242_remove_taskhierarchy_depend_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhierarchy',
            name='depend_on',
            field=models.ManyToManyField(blank=True, null=True, related_name='dependent_children', to='digielves_setup.taskhierarchy'),
        ),
    ]
