# Generated by Django 4.2.9 on 2024-06-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0243_taskhierarchy_depend_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhierarchy',
            name='status_changed_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskhierarchy',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
