# Generated by Django 4.2.9 on 2024-06-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0244_taskhierarchy_status_changed_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhierarchy',
            name='status_changed_to_complete',
            field=models.BooleanField(default=False),
        ),
    ]
