# Generated by Django 4.2.9 on 2024-06-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0245_taskhierarchy_status_changed_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprescriptions',
            name='consumption_quantity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
