# Generated by Django 4.2.9 on 2024-06-29 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0246_doctorprescriptions_consumption_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhierarchyattachments',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_attachment_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
