# Generated by Django 4.2.9 on 2024-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0247_taskhierarchyattachments_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhierarchy',
            name='trashed_with',
            field=models.CharField(blank=True, choices=[('Manually', 'Manually'), ('Relatively_task', 'Relatively_task')], default=None, max_length=20, null=True),
        ),
    ]
