# Generated by Django 4.2.9 on 2024-07-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0249_taskhierarchyduerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhierarchyattachments',
            name='task_attachment',
            field=models.FileField(upload_to='employee/task_attachment/'),
        ),
    ]
