# Generated by Django 4.2.9 on 2024-07-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0250_alter_taskhierarchyattachments_task_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meettings',
            name='meet_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
