# Generated by Django 4.2.9 on 2024-07-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0251_meettings_meet_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfollowup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
