# Generated by Django 4.2.9 on 2024-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0255_fevboard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fevboard',
            name='board',
        ),
        migrations.AddField(
            model_name='fevboard',
            name='board',
            field=models.ManyToManyField(to='digielves_setup.board'),
        ),
    ]
