# Generated by Django 4.2.9 on 2024-07-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0256_remove_fevboard_board_fevboard_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fevboard',
            name='favorite',
        ),
    ]
