# Generated by Django 4.2.9 on 2024-07-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0257_remove_fevboard_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='favorite',
        ),
    ]
