# Generated by Django 4.2.9 on 2024-07-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0258_remove_board_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
