# Generated by Django 4.2.9 on 2024-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0259_board_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='favorite',
            field=models.BooleanField(default=None),
        ),
    ]
