# Generated by Django 4.2.9 on 2024-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0260_alter_board_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='budget',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
