# Generated by Django 4.2.9 on 2024-07-12 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0261_alter_saleslead_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='lead_created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
