# Generated by Django 4.2.9 on 2024-07-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0263_savedtemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedTemplate',
            new_name='TestSavedTemplate',
        ),
    ]
