# Generated by Django 4.2.9 on 2024-07-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0265_savedcategory_savedtemplate_savedtemplatechecklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_category', to='digielves_setup.savedcategory'),
        ),
        migrations.AlterField(
            model_name='savedtemplatechecklist',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_checklist', to='digielves_setup.savedtemplate'),
        ),
        migrations.AlterField(
            model_name='savedtemplatetasklist',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_task', to='digielves_setup.savedtemplatechecklist'),
        ),
    ]
