# Generated by Django 4.2.9 on 2024-07-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0266_alter_savedtemplate_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtemplate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='savedtemplatechecklist',
            name='template',
        ),
        migrations.RemoveField(
            model_name='savedtemplatetasklist',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='SavedCategory',
        ),
        migrations.DeleteModel(
            name='SavedTemplate',
        ),
        migrations.DeleteModel(
            name='SavedTemplateChecklist',
        ),
        migrations.DeleteModel(
            name='SavedTemplateTaskList',
        ),
    ]
