# Generated by Django 4.2.9 on 2024-07-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0270_savedcategory_savedtemplatechecklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcategory',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digielves_setup.board'),
        ),
    ]
