# Generated by Django 4.2.9 on 2024-07-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0271_savedcategory_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='favorite',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
