# Generated by Django 4.2.9 on 2024-08-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0272_alter_board_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee/board/'),
        ),
        migrations.AddField(
            model_name='board',
            name='summery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
