# Generated by Django 4.2.9 on 2024-11-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0273_board_image_board_summery'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
