# Generated by Django 4.2.9 on 2024-11-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0274_user_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='external_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
