# Generated by Django 4.2.9 on 2024-11-11 06:52

import digielves_setup.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digielves_setup', '0275_alter_user_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdetails',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[digielves_setup.validations.is_valid_name]),
        ),
    ]
